data_collection:
    use_threading: False
    num_rollouts_train: 10

aggregation:
    num_aggregation_iters: 50
    num_trajectories_for_aggregation: 10

dyn_model:
    num_fc_layers: 2
    depth_fc_layers: 512
    batchsize: 512
    lr: 0.001
    nEpoch: 100
    fraction_use_new: 0.9

learning_rate: 0.0001
actor_learning_rate: 0.0001
critic_learning_rate: 0.0001

batch_size: 64
discount_factor: 0.99
exploration_rate: 1
memory_size: 50000
training_steps: 50
action_noise: 0.01

hidden_sizes:
    - 64
    - 64