pelican: #namespace

    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000

    n_actions: 4 # Forwards, Backwards, TurnLeft and TurnRight
    
    max_roll_pitch: 1.57 # Maximum Base pitch and roll Angular speed
    max_yaw_angular_speed: 1.0 # Maximum Base Turn Angular speed
    max_thrust: 20.0

    work_space: # 3D cube in which Drone is allowed to move
      x_max: 10.0
      x_min: -10.0
      y_max: 10.0
      y_min: -10.0
      z_max: 20.0
      z_min: 0.3
    
    aircraft_1:
      x: -4.0
      y: 4.0
      z: 0.2
    
    aircraft_2:
      x: 4.0
      y: -4.0
      z: 0.2
    
    collision_tolerance: 0.5

    desired_point:
      x: 0.0
      y: 0.0
      z: 3.0
    desired_point_epsilon: 0.20
    max_distance_from_des_point: 20.0 # Maximum distance regitered in observations, has to be bigger than the largest distance of the workspace.
    
    number_decimals_precision_obs: 5

    energy_cost_weight: 5.e-4
    attitude_cost_weight: 2.e-3
    position_cost_weight: 4.e-1
    acc_cost_weight: 2.e-3
    angular_cost_weight: 1.e-3
    velocity_cost_weight: 5.e-3

    done_reward: 5.0 # reward
    closer_to_point_reward: 1.0 # reward