pelican: #namespace

    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000

    n_actions: 4 # Forwards, Backwards, TurnLeft and TurnRight
    
    propeller_high_speed: 1200 # High Propeller Speed             
    propeller_low_speed: 0.0 # Low Propeller Speed
    max_angular_speed: 1.0 # Maximum Base pitch and roll Angular speed
    max_yaw_angular_speed: 1.0 # Maximum Base Turn Angular speed
   
    work_space: # 3D cube in which Drone is allowed to move
      x_max: 6.0
      x_min: -6.0
      y_max: 6.0
      y_min: -6.0
      z_max: 10.0
      z_min: 0.3

    desired_point:
      x: 0.0
      y: 0.0
      z: 5.0
    desired_point_epsilon: 0.5
    max_distance_from_des_point: 30.0 # Maximum distance regitered in observations, has to be bigger than the largest distance of the workspace.
    
    number_decimals_precision_obs: 1
    energy_cost_weight: 0.2
    propeller_hovering_speed: 508.76
    propeller_normalize_constant: 1000
    attitude_cost_weight: 0.05

    done_reward: 1000.0 # reward
    closer_to_point_reward: 1.0 # reward